# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "handle_models", :force => true do |t|
    t.column "handle", :string, :limit => 64
  end

  create_table "handle_other_column_models", :force => true do |t|
    t.column "other", :string, :limit => 64
  end

end
